# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger: none

pr: none

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  env:
    ACCESS_TOKEN: $(accessToken)
  inputs:
    workingDirectory: 'core-sample/'
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'

- task: AndroidSigning@3
  inputs:
    apkFiles: './core-sample/build/outputs/apk/release/core-sample-release-unsigned.apk'
    apksignerKeystoreFile: 'iar_keystore'
    apksignerKeystorePassword: $(keystorePassword)
    apksignerKeystoreAlias: 'iar'
    apksignerKeyPassword: $(keystoreAliasPassword)
    zipalign: false

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'IAR SDK Core App Center - Android'
    appSlug: $(appslug)
    appFile: './core-sample/build/outputs/apk/release/core-sample-release-unsigned.apk'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'New Core Sample QA Build'
    destinationType: 'groups'