# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger: none

pr:
 branches:
   include:
     - master
     - develop

pool:
  vmImage: 'macos-latest'

steps:
- bash: echo $(accessToken) this is the token

- task: Gradle@2
  env:
    ACCESS_TOKEN: $(accessToken)
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: 'target-ar-sample/'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug testDebugUnitTest'

- task: Gradle@3
  env:
    ACCESS_TOKEN: $(accessToken)
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: 'core-sample/'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug testDebugUnitTest'

- task: Gradle@3
  env:
    ACCESS_TOKEN: $(accessToken)
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: 'surface-ar-sample/'
    gradleOptions: '-Xmx3072m'
    tasks: 'assembleDebug testDebugUnitTest'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'